"""Generate Databricks App resource definitions for the bundle.

Reads the job registry and produces the ``app`` resource block that
wires each job as an app resource with ``CAN_VIEW`` permission.
Environment variables are emitted so the app can discover job IDs
at runtime via ``DBXDEC_JOB_*``.

The Python SDK for Databricks bundles does not support ``App`` as a
resource type, so the app resource must be declared in YAML.  Use
`generate_app_config_yaml` to produce a YAML string suitable for
writing to a file that ``databricks.yml`` includes.
"""

from __future__ import annotations

from typing import Any

from databricks_bundle_decorators.registry import _JOB_REGISTRY


def generate_app_resource(
    app_name: str,
    source_code_path: str = "./app",
    *,
    permission: str = "CAN_VIEW",
) -> dict[str, Any]:
    """Build a bundle-compatible app resource definition.

    The returned dictionary can be merged into the bundle's
    ``resources.apps`` section.  It declares each registered job as
    an app resource and emits ``DBXDEC_JOB_<name>`` environment
    variables via ``valueFrom`` so the app can discover job IDs at
    runtime.

    Parameters
    ----------
    app_name:
        The Databricks App name (must be lowercase, alphanumeric,
        and hyphens only).
    source_code_path:
        Path to the app source code directory, relative to the
        bundle root.
    permission:
        Permission level to grant the app's service principal on
        each job.  Defaults to ``CAN_VIEW``.

    Returns
    -------
    dict[str, Any]
        A dictionary with a single key (the app resource key) whose
        value is the full app resource definition.

    Example
    -------
    ::

        from databricks_bundle_decorators.app import generate_app_resource

        app_resources = generate_app_resource("my-pipeline-observability")
        # Merge into your bundle config alongside generate_resources()
    """
    resources: list[dict[str, Any]] = []
    env: list[dict[str, Any]] = []

    for job_name in sorted(_JOB_REGISTRY.keys()):
        # Resource name for the app resource binding
        resource_name = f"dbxdec-job-{job_name}".replace("_", "-")

        resources.append(
            {
                "name": resource_name,
                "description": f"Job: {job_name}",
                "job": {
                    "id": f"${{resources.jobs.{job_name}.id}}",
                    "permission": permission,
                },
            }
        )

        # Environment variable so the app discovers the job ID
        env_var_name = f"DBXDEC_JOB_{job_name.upper()}"
        env.append(
            {
                "name": env_var_name,
                "valueFrom": resource_name,
            }
        )

    # Sanitize app_name for use as a resource key
    resource_key = app_name.replace("-", "_")

    return {
        resource_key: {
            "name": app_name,
            "description": "Pipeline observability dashboard",
            "source_code_path": source_code_path,
            "config": {
                "command": ["python", "app.py"],
                "env": env,
            },
            "resources": resources,
        }
    }


def generate_app_config_yaml(
    app_name: str,
    source_code_path: str = "./app",
    *,
    permission: str = "CAN_VIEW",
) -> str:
    """Return a YAML string declaring the app as a bundle resource.

    The Databricks Python SDK does not support ``App`` resources via
    ``Resources.add_resource()``, so the app must be declared in YAML.
    Write the returned string to a file (e.g. ``resources/app.yml``)
    and add it to the ``include`` list in ``databricks.yaml``.

    Parameters
    ----------
    app_name:
        The Databricks App name (lowercase, alphanumeric, hyphens).
    source_code_path:
        Path to the app source code directory, relative to the
        bundle root.
    permission:
        Permission level to grant the app's service principal on
        each job.  Defaults to ``CAN_VIEW``.

    Returns
    -------
    str
        A YAML string for the ``resources.apps`` section.
    """
    app = generate_app_resource(app_name, source_code_path, permission=permission)
    resource_key = app_name.replace("-", "_")
    definition = app[resource_key]

    lines = [
        "# Auto-generated by: dbxdec init --dashboard",
        "# Regenerate with:   dbxdec app-config",
        "#",
        "# Do not edit manually — changes will be overwritten.",
        "",
        "resources:",
        "  apps:",
        f"    {resource_key}:",
        f"      name: {definition['name']}",
        f"      description: {definition['description']}",
        f"      source_code_path: {definition['source_code_path']}",
        "      config:",
        '        command: ["python", "app.py"]',
    ]

    if definition["config"]["env"]:
        lines.append("        env:")
        for env_item in definition["config"]["env"]:
            lines.append(f"          - name: {env_item['name']}")
            lines.append(f"            valueFrom: {env_item['valueFrom']}")

    if definition["resources"]:
        lines.append("      resources:")
        for res in definition["resources"]:
            lines.append(f"        - name: {res['name']}")
            lines.append(f'          description: "{res["description"]}"')
            lines.append("          job:")
            lines.append(f'            id: "{res["job"]["id"]}"')
            lines.append(f"            permission: {res['job']['permission']}")

    lines.append("")  # trailing newline
    return "\n".join(lines)
